### ISSUE TITLE
PDF - No longer scraping

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/newcastle_development_applications#1]
Was https://github.com/nik3daz/newcastle_development_applications/issues/1

```
Injecting configuration and compiling...
 Injecting scraper and running...
 /app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:308:in `fetch' : 404 => Net::HTTPNotFound for http://www.newcastle.nsw.gov.au/building_and_planning/da_assessment/current_das/current_das -- unhandled response (Mechanize::ResponseCodeError)
    from /app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
    from scraper.rb:89:in `<main>'
```

**Comment by CloCkWeRX** [comment]
#2 partially updates this to point at PDFs, but extracting content from them is a bit tricky as the format changed.

RSS feed: http://www.newcastle.nsw.gov.au/Special-Pages/MediaFeed.aspx?rss=MediaFiles&directory=Documents&path=Development%20Applications/Weekly%20Notifications

**Comment by mercuryfrost** [comment]
Hi Guys, I dont know much about Github and was playing around and created my own fork and Patch.

I believe I have a working version and have fixed most of the issues surrounding both the change of URL (I moved to the RSS Feed) and updated the extract to get the data into a useable format.

Been testing it and it appears to be working correctly.

**Comment by CloCkWeRX** [comment]
@mercuryfrost - have a quick look at https://help.github.com/articles/creating-a-pull-request/ :) 

Edit: Nevermind, you are 10 steps ahead!
