### ISSUE TITLE
Address is missing suburb so addresses are not being geocoded correctly

### ISSUE THREAD

**Issue by henare** [planningalerts-scrapers/newcastle_development_applications#4]
The suburb is now appearing in the description.

I've disabled this scraper until it's fixed, **remember to re-enable auto-run when this is fixed**.

**Comment by JasonThomasData** [comment]
I've got some time this week so I'll look at this.

**Comment by JasonThomasData** [comment]
Wow this one is a challenge, I think you did a good job to get this working. I've made it so the vast majority of records get parsed and saved proper but there's going to be some that are bad, sorry, it's too bigger job for me to do this week. If this is sufficient I'll push a fix

**Comment by jamezpolley** [comment]
This refers to the old site; new site is better and an ATDIS feed is on the way.
